services:
  # Docker Socket Proxy - provides read-only access to Docker API
  # Using minimal socket proxy for better compatibility
  socket-proxy:
    image: 11notes/socket-proxy:stable
    container_name: portall-socket-proxy
    environment:
      - ALLOW_RESTARTS=0
      - ALLOW_START=0
      - ALLOW_STOP=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "127.0.0.1:2375:2375"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run/proxy
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    networks:
      - portall-network

  # Main Portall application
  portall:
    build: .
    container_name: portall
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    depends_on:
      - socket-proxy
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=your_secret_key
      - DOCKER_HOST=tcp://socket-proxy:2375
      - DOCKER_ENABLED=true
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # Note: Not using read_only for main app as it needs to write to database
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    networks:
      - portall-network

# Alternative: Using the tecnativa socket proxy (more features but more complex)
# Uncomment this and comment out the minimal proxy above if preferred
# socket-proxy-tecnativa:
#   image: tecnativa/docker-socket-proxy:latest
#   container_name: portall-socket-proxy-tecnativa
#   environment:
#     # Enable only the API endpoints we need (read-only)
#     - CONTAINERS=1
#     - SERVICES=1
#     - NETWORKS=1
#     - INFO=1
#     - VERSION=1
#     # Disable write operations
#     - POST=0
#     - BUILD=0
#     - COMMIT=0
#     - CONFIGS=0
#     - DISTRIBUTION=0
#     - EXEC=0
#     - IMAGES=0
#     - NODES=0
#     - PLUGINS=0
#     - SECRETS=0
#     - SWARM=0
#     - SYSTEM=0
#     - TASKS=0
#     - VOLUMES=0
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock:ro
#   ports:
#     - "127.0.0.1:2375:2375"
#   restart: unless-stopped
#   security_opt:
#     - no-new-privileges:true
#   read_only: true
#   tmpfs:
#     - /tmp
#     - /usr/local/etc/haproxy  # Allow HAProxy to write config files
#   cap_drop:
#     - ALL
#   cap_add:
#     - CHOWN
#     - SETGID
#     - SETUID
#   networks:
#     - portall-network

networks:
  portall-network:
    driver: bridge